#pragma once

#include <Arduino.h>

#define DEVICE_NAME "WATER-LEVEL-CONTROLLER"

#define RELAY_1_PIN 25
#define RELAY_2_PIN 26
#define RELAY_3_PIN 32
#define RELAY_4_PIN 33

#define LOWER_LEVEL_SENSOR_PIN 22
#define UPPER_LEVEL_SENSOR_PIN 18

#define SETUP_BUTTON_PIN 23

#define RELAY_ACTIVE_LOW 1
#define BUTTON_ACTIVE_LEVEL LOW

#define SETUP_AP_SSID "WLC-SETUP"
#define SETUP_AP_PASSWORD "wlc-setup"

#define DEFAULT_FILL_TIMEOUT_MINUTES 10
#define DEFAULT_PUMP_FLOW_LPM 10.0f
#define DEFAULT_PUMP_RELAY 1
#define DEFAULT_ALARM_RELAY 2
#define MAX_FILL_TIMEOUT_MINUTES 60
#define MIN_FILL_TIMEOUT_MINUTES 1
#define MIN_PUMP_FLOW_LPM 0.1f
#define MAX_PUMP_FLOW_LPM 999.9f
#define WIFI_AP_START_DELAY_MS 5000UL
#define SETUP_TEST_RUN_TIMEOUT_MINUTES 10

#define DEFAULT_SENSOR_TRIGGER_MODE 0